name: 'Elm Publish'
description: 'Publish Elm package from the master branch if the current version is unpublished.'
author: 'Dillon Kearns'
inputs:
  github-token:
    description: "Token provided by GitHub. This is required, unless you are performing a dry-run."
    required: false
  path-to-elm:
    description: "Path to Elm compiler to use instead of looking in the PATH."
    required: false
  dry-run:
    description: "Perform the check without actually publishing. Do not include github-token when you perform a dry-run."
    required: false
outputs:
  is-publishable:
    description: "Whether this Elm package is in a state that can be published. In a dry-run, this will tell you whether elm-publish-action will attempt to publish in a real run."
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'  
  color: 'blue'
