name: 'Elm Actions'
description: 'Publish Elm package from the master branch if the current version is unpublished.'
author: 'Dillon Kearns'
inputs:
  github-token:
    description: "Token provided by GitHub"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'  
  color: 'blue'
