name: 'Elm Actions'
description: 'Scripts for maintaining Elm projects and Elm packages.'
author: 'Dillon Kearns'
inputs:
  github-token:
    description: "Token provided by GitHub"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
