name: 'Elm Publish'
description: 'Publish Elm package from the master branch if the current version is unpublished.'
author: 'Dillon Kearns'
inputs:
  github-token:
    description: "Token provided by GitHub"
    required: true
  path-to-elm:
    description: "Path to Elm compiler to use instead of looking in the PATH."
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'  
  color: 'blue'
